network:
  node_id: ret7dd2cb0d
capture:
  device:
    gainReduction: 30
location:
  rx:
    latitude: 37.7644
    longitude: -122.3954
    altitude: 23
    name: 150 Mississippi
  tx:
    latitude: 37.49917
    longitude: -121.87222
    altitude: 783
truth:
  adsb:
    tar1090: sfo1.retnode.com
tar1090:
  adsb_source: 192.168.8.183,30005,beast_in
